### ISSUE TITLE
raft: src/uv_os.c avoid use of reallocarray()

### ISSUE THREAD

**Issue by rajeshbha** [Nexenta/edgefs#472]
### Summary 
reallocarray() is not available on Ubuntu 16.04

### Steps to reproduce the behavior
Compile on 16.04

### Expected behavior
No compilation warning

### Actual behavior
src/uv_os.c:163:20: error: implicit declaration of function ‘reallocarray’ [-Werror=implicit-function-declaration]
   dirp->dir_ents = reallocarray(dirp->dir_ents,

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ *] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other
